apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: hackz-giganoto
spec:
  selector:
    app: chat
  ports:
  - name: grpc
    port: 50053
    targetPort: 50053
    protocol: TCP
  type: ClusterIP