apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-deployment
  namespace: hackz-giganoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat
      version: v1
  template:
    metadata:
      labels:
        app: chat
        version: v1
    spec:
      containers:
      - name: chat
        image: ghcr.io/naoido/hackz-giganoto-chat:latest
        ports:
        - containerPort: 50053
          name: grpc
        env:
        - name: PORT
          value: "50053"
        - name: REDIS_ADDR
          value: "chat-redis-service:6379"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-service:4317"
        - name: OTEL_SERVICE_NAME
          value: "chat-service"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.0"
        livenessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=:50053
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - grpc_health_probe
            - -addr=:50053
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"