apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - chat-deployment.yaml
  - chat-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml

commonLabels:
  component: chat