apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector-deployment
  namespace: hackz-giganoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
      version: v1
  template:
    metadata:
      labels:
        app: otel-collector
        version: v1
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        command:
        - /otelcol-contrib
        - --config=/etc/otel-collector-config.yaml
        ports:
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        - containerPort: 8888
          name: metrics
        - containerPort: 8889
          name: prometheus
        - containerPort: 13133
          name: health-check
        - containerPort: 1777
          name: pprof
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otel-collector-config.yaml
          subPath: otel-config.yaml
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: otel-config
        configMap:
          name: otel-config