swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /profile:
        post:
            tags:
                - profile
            summary: create profile
            operationId: profile#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfilePayload'
                    required:
                        - username
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/GoaExampleProfile'
            schemes:
                - http
    /profile/{id}:
        get:
            tags:
                - profile
            summary: get profile
            operationId: profile#get
            parameters:
                - name: id
                  in: path
                  description: Profile ID
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/GoaExampleProfile'
            schemes:
                - http
definitions:
    GoaExampleProfile:
        title: 'Mediatype identifier: application/vnd.goa.example.profile; view=default'
        type: object
        properties:
            id:
                type: string
                description: Unique profile ID
                example: Omnis enim omnis autem accusamus.
            username:
                type: string
                description: The user's name
                example: Aut magnam laborum ad porro.
        description: CreateResponseBody result type (default view)
        example:
            id: Recusandae nihil non molestiae id accusamus incidunt.
            username: Accusantium maxime et amet nostrum vel.
        required:
            - id
            - username
    ProfilePayload:
        title: ProfilePayload
        type: object
        properties:
            username:
                type: string
                description: The user's name
                example: Esse dolor et minima exercitationem asperiores.
        example:
            username: Corrupti voluptatem qui dolores perspiciatis velit.
        required:
            - username
