apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: hackz-giganoto
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP