apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-deployment.yaml
  - auth-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml

commonLabels:
  component: auth