apiVersion: v1
kind: Service
metadata:
  name: auth-redis-service
  namespace: hackz-giganoto
spec:
  selector:
    app: auth-redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  type: ClusterIP