apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: hackz-giganoto
spec:
  selector:
    app: bff
  ports:
  - name: grpc
    port: 50054
    targetPort: 50054
    protocol: TCP
  type: ClusterIP