apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bff-deployment.yaml
  - bff-service.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml

commonLabels:
  component: bff