apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bff-redis-data
  namespace: hackz-giganoto
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi