swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth/github:
        get:
            tags:
                - auth
            summary: auth_url auth
            description: Get GitHub OAuth authorization URL with state parameter
            operationId: auth#auth_url
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthAuthURLResponseBody'
                        required:
                            - auth_url
                            - state
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
    /auth/github/callback:
        get:
            tags:
                - auth
            summary: oauth_callback auth
            description: Handle GitHub OAuth callback and return opaque token
            operationId: auth#oauth_callback
            parameters:
                - name: code
                  in: query
                  description: Authorization code from GitHub
                  required: true
                  type: string
                - name: state
                  in: query
                  description: OAuth state parameter for validation
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthOauthCallbackResponseBody'
                        required:
                            - access_token
                            - token_type
                            - expires_in
                            - user_id
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
                "502":
                    description: Bad Gateway response.
                    schema:
                        type: string
            schemes:
                - http
    /introspect:
        post:
            tags:
                - auth
            summary: introspect auth
            description: Introspect opaque token and return internal JWT token for Kong Gateway
            operationId: auth#introspect
            parameters:
                - name: IntrospectRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthIntrospectRequestBody'
                    required:
                        - token
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthIntrospectResponseBody'
                        required:
                            - jwt
                            - active
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    AuthAuthURLResponseBody:
        title: AuthAuthURLResponseBody
        type: object
        properties:
            auth_url:
                type: string
                description: GitHub OAuth authorization URL
                example: Ut iusto cum voluptate.
            state:
                type: string
                description: OAuth state parameter for CSRF protection
                example: Qui sit reprehenderit a ut et ea.
        example:
            auth_url: Repudiandae fugiat molestiae aliquid voluptas.
            state: Modi est adipisci autem rem fuga.
        required:
            - auth_url
            - state
    AuthIntrospectRequestBody:
        title: AuthIntrospectRequestBody
        type: object
        properties:
            token:
                type: string
                description: Opaque token to introspect
                example: Illo voluptatem eligendi.
        example:
            token: Quas autem eius suscipit laboriosam laborum voluptas.
        required:
            - token
    AuthIntrospectResponseBody:
        title: AuthIntrospectResponseBody
        type: object
        properties:
            active:
                type: boolean
                description: Whether the token is active
                example: false
            exp:
                type: integer
                description: Token expiration timestamp
                example: 3379430536361615656
                format: int64
            jwt:
                type: string
                description: Internal JWT token for downstream services
                example: Ipsum voluptatem.
            scopes:
                type: array
                items:
                    type: string
                    example: Recusandae quod porro.
                description: Token scopes
                example:
                    - Laudantium voluptatem assumenda.
                    - Rem tempora autem vel blanditiis.
                    - Corrupti nostrum.
                    - Debitis illo iusto maxime voluptas aliquid totam.
        example:
            active: true
            exp: 8289282376285563972
            jwt: Et provident ab ea alias minus.
            scopes:
                - Aut eos est dolor libero.
                - Minus cupiditate adipisci omnis ex porro.
        required:
            - jwt
            - active
    AuthOauthCallbackResponseBody:
        title: AuthOauthCallbackResponseBody
        type: object
        properties:
            access_token:
                type: string
                description: Opaque access token
                example: Architecto aspernatur vel.
            expires_in:
                type: integer
                description: Token expiration in seconds
                example: 9066871487314540977
                format: int64
            token_type:
                type: string
                description: Token type (Bearer)
                example: Officia nihil sed quas sequi nemo occaecati.
            user_id:
                type: string
                description: GitHub user ID
                example: Quo modi ab et qui nobis dolor.
        example:
            access_token: Et quo similique.
            expires_in: 9067872402607182631
            token_type: Sint quidem.
            user_id: Id labore et adipisci.
        required:
            - access_token
            - token_type
            - expires_in
            - user_id
