swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /auth/github:
        get:
            tags:
                - auth
            summary: auth_url auth
            description: Get GitHub OAuth authorization URL with state parameter
            operationId: auth#auth_url
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthAuthURLResponseBody'
                        required:
                            - auth_url
                            - state
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
    /auth/github/callback:
        get:
            tags:
                - auth
            summary: oauth_callback auth
            description: Handle GitHub OAuth callback and return opaque token
            operationId: auth#oauth_callback
            parameters:
                - name: code
                  in: query
                  description: Authorization code from GitHub
                  required: true
                  type: string
                - name: state
                  in: query
                  description: OAuth state parameter for validation
                  required: true
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthOauthCallbackResponseBody'
                        required:
                            - access_token
                            - token_type
                            - expires_in
                            - user_id
                "400":
                    description: Bad Request response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
                "502":
                    description: Bad Gateway response.
                    schema:
                        type: string
            schemes:
                - http
    /introspect:
        post:
            tags:
                - auth
            summary: introspect auth
            description: Introspect opaque token and return internal JWT token for Kong Gateway
            operationId: auth#introspect
            parameters:
                - name: IntrospectRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthIntrospectRequestBody'
                    required:
                        - token
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthIntrospectResponseBody'
                        required:
                            - jwt
                "401":
                    description: Unauthorized response.
                    schema:
                        type: string
                "500":
                    description: Internal Server Error response.
                    schema:
                        type: string
            schemes:
                - http
definitions:
    AuthAuthURLResponseBody:
        title: AuthAuthURLResponseBody
        type: object
        properties:
            auth_url:
                type: string
                description: GitHub OAuth authorization URL
                example: Dolores et.
            state:
                type: string
                description: OAuth state parameter for CSRF protection
                example: Illum ducimus et voluptatem.
        example:
            auth_url: Iure iure nam.
            state: Distinctio ipsum ut nobis aperiam sit.
        required:
            - auth_url
            - state
    AuthIntrospectRequestBody:
        title: AuthIntrospectRequestBody
        type: object
        properties:
            token:
                type: string
                description: Opaque token to introspect
                example: Impedit rem eligendi consectetur voluptas rem error.
        example:
            token: Sunt deserunt repudiandae quod consectetur quia.
        required:
            - token
    AuthIntrospectResponseBody:
        title: AuthIntrospectResponseBody
        type: object
        properties:
            jwt:
                type: string
                description: Internal JWT token for downstream services
                example: Voluptatibus illum natus.
        example:
            jwt: Perferendis autem et et qui maiores non.
        required:
            - jwt
    AuthOauthCallbackResponseBody:
        title: AuthOauthCallbackResponseBody
        type: object
        properties:
            access_token:
                type: string
                description: Opaque access token
                example: Voluptatem accusamus.
            expires_in:
                type: integer
                description: Token expiration in seconds
                example: 7236623053205628506
                format: int64
            token_type:
                type: string
                description: Token type (Bearer)
                example: Eos recusandae quod porro.
            user_id:
                type: string
                description: GitHub user ID
                example: Laudantium voluptatem assumenda.
            userName:
                type: string
                description: GitHub user name
                example: Rem tempora autem vel blanditiis.
        example:
            access_token: Corrupti nostrum.
            expires_in: 6967004365280331159
            token_type: Debitis illo iusto maxime voluptas aliquid totam.
            user_id: Provident ab ea alias minus.
            userName: Aut doloribus consequatur aut.
        required:
            - access_token
            - token_type
            - expires_in
            - user_id
