apiVersion: v1
kind: Service
metadata:
  name: kong-service
  namespace: hackz-giganoto
spec:
  selector:
    app: kong
  ports:
  - name: proxy
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: admin
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: manager
    port: 8002
    targetPort: 8002
    protocol: TCP
  type: LoadBalancer