apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hackz-giganoto
resources:
  - neko-bot.yaml
  - redis.yaml
secretGenerator:
  - name: microservices-env
    envs:
      - ./secrets/.env
    options:
      disableNameSuffixHash: true