apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-deployment
  namespace: hackz-giganoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      version: v1
  template:
    metadata:
      labels:
        app: loki
        version: v1
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        command:
        - /usr/bin/loki
        - -config.file=/etc/loki/local-config.yaml
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9096
          name: grpc
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/local-config.yaml
          subPath: local-config.yaml
          readOnly: true
        - name: loki-storage
          mountPath: /loki
        livenessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3100
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
      - name: loki-storage
        emptyDir: {}