apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: hackz-giganoto
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger-service:16686
        isDefault: false
        editable: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-service:3100
        isDefault: false
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provider
  namespace: hackz-giganoto
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards